version: '3.9'

services:
  python-flask:
    build:
      context: .
      dockerfile: Dockerfile-dev
    tty: true
    stdin_open: true
    volumes:
      - ./:/app/
    ports:
      - "5000:5000"

  ngrok:
    image: wernight/ngrok:latest
    ports:
      - "8888:4040"
    environment:
      NGROK_PROTOCOL: tcp
      NGROK_PORT: python-flask:5000
      NGROK_AUTH: <NGROK_AUTH>