FROM python:3.9
# add project
ADD ./web /app

WORKDIR /app

# install flask
RUN pip install --upgrade pip
RUN pip install Flask requests line-bot-sdk PyMYSQL


##run flask
##Developer use
#CMD ["python"]

#Production use
CMD ["python", "app.py"]
